## This file is a template remove the .template to use the file

libraries:                       # This is called out once within the config.yml file
  NEU:                        # These are names of libraries in your Plex
    collection_files:
    #- pmm: basic                 # This is a file within PMM's defaults folder
    #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files: # Set this to true to remove all overlays
    - reapply_overlay: true
    - file: config/metadata/country.yml
    - file: config/overlays/content_rating_de.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
        #- pmm: Country
        # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
  Klassiker:                        # These are names of libraries in your Plex
    collection_files:
    #- pmm: basic                 # This is a file within PMM's defaults folder
    #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files: # Set this to true to remove all overlays
    - reapply_overlay: true
    - file: config/metadata/country.yml
    - file: config/overlays/content_rating_de.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
        #- pmm: Country
        # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
  Komödie:                        # These are names of libraries in your Plex
    collection_files:
    #- pmm: basic                 # This is a file within PMM's defaults folder
    #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files: # Set this to true to remove all overlays
    - reapply_overlay: true
    - file: config/metadata/country.yml
    - file: config/overlays/content_rating_de.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
        #- pmm: Country
        # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
  Kinderfilme:                        # These are names of libraries in your Plex
    collection_files:
    #- pmm: basic                 # This is a file within PMM's defaults folder
    #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files: # Set this to true to remove all overlays
    - reapply_overlay: true
    - file: config/metadata/country.yml
    - file: config/overlays/content_rating_de.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
        #- pmm: Country
        # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
  Dokumenta:                        # These are names of libraries in your Plex
    collection_files:
    #- pmm: basic                 # This is a file within PMM's defaults folder
    #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files: # Set this to true to remove all overlays
    - reapply_overlay: true
    - file: config/metadata/country.yml
    - file: config/overlays/content_rating_de.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
        #- pmm: Country
        # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
  Cinemathek:
    collection_files:
    #- pmm: basic                 # This is a file within PMM's defaults folder
    #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files: # Set this to true to remove all overlays
    - reapply_overlay: true
    - file: config/metadata/country.yml
    - file: config/overlays/content_rating_de.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
        #- pmm: Country
        # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
  Musik (Filme):
    collection_files:
    #- pmm: basic                 # This is a file within PMM's defaults folder
    #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files: # Set this to true to remove all overlays
    - reapply_overlay: true
    - file: config/metadata/country.yml
    - file: config/overlays/content_rating_de.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
        #- pmm: Country
        # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
  RomCom:
    collection_files:
    #- pmm: basic                 # This is a file within PMM's defaults folder
    #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files: # Set this to true to remove all overlays
    - reapply_overlay: true
    - file: config/metadata/country.yml
    - file: config/overlays/content_rating_de.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
        #- pmm: Country
        # see the wiki for how to use local files, folders, URLs, or files from git
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
  Serien:
    collection_files:
      #- pmm: basic                 # This is a file within PMM's defaults folder
      #- pmm: imdb                  # This is a file within PMM's defaults folder
    #- pmm: genre
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        #- pmm: country
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files:
    - reapply_overlays: true
    - remove_overlays: false     # Set this to true to remove all overlays
    - file: config/metadata/country.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
    - file: config/overlays/content_rating_de.yml
    - file: config/overlays/content_rating_de.yml
    - file: config/metadata/country.yml
      template_variables:
        builder_level: season
    - pmm: languages
    - pmm: resolution
    - file: config/overlays/content_rating_de.yml
      template_variables:
        builder_level: episode
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true
      # see the wiki for how to use local files, folders, URLs, or files from git
  Serien(OV):
    collection_files:
      #- pmm: basic                 # This is a file within PMM's defaults folder
      #- pmm: imdb                  # This is a file within PMM's defaults folder
    - pmm: country
    - file: config/metadata/content_rating_de.yml
        #- pmm: country
        # see the wiki for how to use local files, folders, URLs, or files from git
    overlay_files:
    - reapply_overlays: true
    - remove_overlays: false     # Set this to true to remove all overlays
    - file: config/metadata/country.yml
    - pmm: ribbon                # This is a file within PMM's defaults folder
    - pmm: languages
    - pmm: resolution
    - file: config/overlays/content_rating_de.yml
    - file: config/overlays/content_rating_de.yml
    - file: config/metadata/country.yml
      template_variables:
        builder_level: season
    - pmm: languages
    - pmm: resolution
    - file: config/overlays/content_rating_de.yml
      template_variables:
        builder_level: episode
    operations:
      assets_for_all: true
      delete_collections:
        configured: false
        managed: true

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 2
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: deu
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
  run_order:
  - operations
  - metadata
  - collections
  - overlays
webhooks:                        # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.0.112:32400
  token: QasAR9UFztWvL-g-aKnz
  timeout: 60
  db_cache:
  clean_bundles: true
  empty_trash: true
  optimize: false
tmdb:                            # REQUIRED for the script to run
  apikey: 102da0fccef74d9e7eae099eb5a82387
  language: de
  cache_expiration: 60
  region:
tautulli:                        # Can be individually specified per library as well
  url: http://plexpy.noyse.net:8181/
  apikey: 615849e3289044f0835cafc25ed98889
trakt:
  client_id: 10d97bea857ed4140b784d9bb02fa610a4974a4c660a126e21cd3bdd367949fa
  client_secret: 998c8064b51c74c490126d45650f217a46cd7777458a21ab2f67d240a1c8b64f
  authorization:
    access_token: 5b98fff84ec805c91965e9ff7d8842995ae0ec6d3bf67b0887e08326e40df977
    token_type: Bearer
    expires_in: 7889238
    refresh_token: c7212bae30e0289591aaac63b88872e4b70dd05f1d63bd33038d62e400fb7049
    scope: public
    created_at: 1704487820
  pin:
