external_templates:
  pmm: templates
  template_variables:
    collection_section: "01"
    sort_title: "!<<collection_section>>_!TOP<<collection_name>>"

translations:
  pmm: translations

templates:
  flixpatrol:
    default:
      location: united_states
      location_<<key>>: <<location>>
      time_window: last_week
      time_window_<<key>>: <<time_window>>
      limit: 10
      limit_<<key>>: <<limit>>
    flixpatrol_top:
      platform: <<platform>>
      location: <<location_<<key>>>>
      time_window: <<time_window_<<key>>>>
      limit: <<limit_<<key>>>>

dynamic_collections:
  FlixPatrol:
    type: custom
    data:
      netflix: Netflix
      disney: Disney
      hbo: HBO
      hulu: Hulu
      paramount: Paramount Plus
      prime: Prime Video
    template:
      - flixpatrol
      - translation
      - shared
      - arr
      - custom
    template_variables:
      limit:
        default: 10
      platform:
        default: <<key>>
        paramount: paramount_plus
        prime: amazon_prime
      image:
        default: chart/<<key>>_top
      translation_key:
        default: flixpatrol
